development/projects/general/event-platform/force-app/main/default/objects/Cloud_News__e/Cloud_News__e.object-meta.xml
<CustomObject>
    <description>Cloud news events deliver news at your fingertips.</description>
    <label>Cloud News</label>
    <pluralLabel>Cloud News</pluralLabel>
</CustomObject>

development/projects/general/platform-dev1-cert/event-platform/force-app/main/default/objects/Cloud_News__e/fields/Urgent__c.field-meta.xml
<CustomField>
    <fullName>Urgent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Urgent</label>
    <type>Checkbox</type>
</CustomField>

development/projects/general/platform-dev1-cert/event-platform/force-app/main/default/classes/CloudNewsEventHandler.cls
/**
 * @description       : Insert cases about Cloud_News__e event messages.
 * @author            : Flávio Ferreira
 * @group             : 
 * @last modified on  : 01-04-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class CloudNewsEventHandler {
    
    public static void openEventCases(List< Cloud_News__e> cloudNewsEventMessages) {
        Group queue = [SELECT Id FROM Group WHERE Name='Regional Dispatch' AND Type='Queue'];
        
        List<Case> cases = new List<Case>();
        for (Cloud_News__e eventMessage : cloudNewsEventMessages) {
            if (eventMessage.Urgent__c == true) {
                Case eventCase = new Case();
                eventCase.Priority = 'High';
                eventCase.Subject = 'News team dispatch to ' + eventMessage.Location__c;
                eventCase.OwnerId = queue.Id;
                eventCase.Status = 'Open';
                
                cases.add(eventCase);
            }
        }
            
        insert cases; 
    }
}