development/projects/general/platform-dev1-cert/visualforce/force-app/main/default/objects/Football_Association__c/Football_Association__c.object-meta.xml
<CustomObject>
    <description>Football association affiliated to FIFA.</description>
    <label>Football Association</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Football Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

development/projects/general/platform-dev1-cert/visualforce/force-app/main/default/objects/Football_Association__c/fields/Acronym__c.field-meta.xml
<CustomField>
    <fullName>Acronym__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Acronym</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

development/projects/general/platform-dev1-cert/visualforce/force-app/main/default/objects/Football_Association__c/fields/Continental_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>Continental_Affiliation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Continental Affiliation</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

development/projects/general/platform-dev1-cert/visualforce/force-app/main/default/objects/Football_Association__c/fields/President__c.field-meta.xml
<CustomField>
    <fullName>President__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>President</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

development/projects/general/platform-dev1-cert/visualforce/force-app/main/default/objects/Football_Association__c/fields/Year_Founded__c.field-meta.xml
<CustomField>
    <fullName>Year_Founded__c</fullName>
    <label>Year Founded</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

development/projects/general/platform-dev1-cert/visualforce/force-app/main/default/classes/FootballAssociationController.cls
/**
 * @description       : Getting a list of custom object records.
 * @author            : Flávio Ferreira
 * @group             : 
 * @last modified on  : 01-18-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class FootballAssociationController {

    public static List<Football_Association__c> getFootballAssociations() {
        List<Football_Association__c> footballAssociations = [
            SELECT 
                Acronym__c
                ,Name
                ,Continental_Affiliation__c
                ,Year_Founded__c
                ,President__c
            FROM
                Football_Association__c 
            WHERE 
                Year_Founded__c != null AND 
                Acronym__c != null AND
                President__c != ''
            LIMIT 50
        ];

        return footballAssociations;
    }
}