development/projects/general/platform-dev1-cert/visualforce/force-app/main/default/objects/Football_Association__c/Football_Association__c.object-meta.xml
<CustomObject>
    <description>Football association affiliated to FIFA.</description>
    <label>Football Association</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Football Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

development/projects/general/platform-dev1-cert/visualforce/force-app/main/default/objects/Football_Association__c/fields/Acronym__c.field-meta.xml
<CustomField>
    <fullName>Acronym__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Acronym</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

development/projects/general/platform-dev1-cert/visualforce/force-app/main/default/objects/Football_Association__c/fields/Continental_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>Continental_Affiliation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Continental Affiliation</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

development/projects/general/platform-dev1-cert/visualforce/force-app/main/default/objects/Football_Association__c/fields/President__c.field-meta.xml
<CustomField>
    <fullName>President__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>President</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

development/projects/general/platform-dev1-cert/visualforce/force-app/main/default/objects/Football_Association__c/fields/Website__c.field-meta.xml
<CustomField>
    <fullName>Website__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Website</label>
    <type>Url</type>
</CustomField>

development/projects/general/platform-dev1-cert/visualforce/force-app/main/default/objects/Football_Association__c/fields/Year_Continental_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>Year_Continental_Affiliation__c</fullName>
    <label>Year Continental Affiliation</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

development/projects/general/platform-dev1-cert/visualforce/force-app/main/default/objects/Football_Association__c/fields/Year_FIFA_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>Year_FIFA_Affiliation__c</fullName>
    <label>Year FIFA Affiliation</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

development/projects/general/platform-dev1-cert/visualforce/force-app/main/default/objects/Football_Association__c/fields/Year_Founded__c.field-meta.xml
<CustomField>
    <fullName>Year_Founded__c</fullName>
    <label>Year Founded</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

development/projects/general/fifa/1 - src/fifa-core/force-app/main/default/classes/FootballAssociationObjectHandler.cls
/**
 * @description       : Handling Football_Association__c object.
 * @author            : Flávio Ferreira
 * @group             : 
 * @last modified on  : 08-11-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class FootballAssociationObjectHandler {

    public static Football_Association__c getFootballAssociationObject(List<String> htmlData) {
        FootballAssociationHtmlReader reader = new FootballAssociationHtmlReader(htmlData);
        Football_Association__c footballAssociation = new Football_Association__c();

        System.debug('      ||--> GETTING WEBSITE ...');
        footballAssociation.website__c = reader.getWebsiteField();
        System.debug('      ||--> DONE!');
        System.debug('      ||--> GETTING ACRONYM ...');
        footballAssociation.acronym__c = reader.getAcronymField();
        System.debug('      ||--> DONE!');
        System.debug('      ||--> GETTING FULL NAME ...');
        footballAssociation.name = reader.getFullNameField();
        System.debug('      ||--> DONE!');
        System.debug('      ||--> GETTING YEAR FOUNDED ...');
        footballAssociation.year_founded__c = reader.getYearFoundedField();
        System.debug('      ||--> DONE!');
        System.debug('      ||--> GETTING YEAR FIFA AFFILIATION ...');
        footballAssociation.year_Fifa_affiliation__c = reader.getYearFifaAffiliationField();
        System.debug('      ||--> DONE!');
        System.debug('      ||--> GETTING YEAR CONTINENTAL AFFILIATION ...');
        footballAssociation.year_continental_affiliation__c = reader.getYearContinentalAffiliationField();
        System.debug('      ||--> DONE!');
        System.debug('      ||--> GETTING NAME CONTINENTAL AFFILIATION ...');
        footballAssociation.continental_affiliation__c = reader.getNameContinentalAffiliationField();
        System.debug('      ||--> DONE!');
        System.debug('      ||--> GETTING PRESIDENT ...');
        footballAssociation.president__c = reader.getPresidentField();
        System.debug('      ||--> DONE!');

        System.debug('      ||--> CREATING EXTERNAL ID ...');
        footballAssociation.External_ID__c = getExternalId(footballAssociation.acronym__c, footballAssociation.website__c);
        System.debug('      ||--> DONE!');

        return footballAssociation;
    }

    private static String getExternalId(String acronym, String website) {
        String externalId = '';
        
        if(acronym != null && website != null) {
            externalId = acronym + '-' + website;
        } else 
        if(acronym != null) {
            externalId = acronym;
        } else {
            externalId = website;
        }

        return externalId;
    }
}